# Generated by Django 4.2.6 on 2023-11-22 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblpurchase_details',
            old_name='tax_amount',
            new_name='vat_amount',
        ),
        migrations.RenameField(
            model_name='tblpurchase_details',
            old_name='tax_perc',
            new_name='vat_perc',
        ),
        migrations.RenameField(
            model_name='tblpurchase_master',
            old_name='tax',
            new_name='vat',
        ),
        migrations.RenameField(
            model_name='tblsales_details',
            old_name='tax_amount',
            new_name='vat_amount',
        ),
        migrations.RenameField(
            model_name='tblsales_details',
            old_name='tax_perc',
            new_name='vat_perc',
        ),
        migrations.RenameField(
            model_name='tblsales_master',
            old_name='tax',
            new_name='vat',
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='health_insurance_expiry',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 14, 40, 11, 121697, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='passport_expiry',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 14, 40, 11, 121697, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='visa_expiry',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 14, 40, 11, 121697, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblpurchase_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 14, 40, 11, 123685, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblsales_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 14, 40, 11, 122690, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='createdon',
            field=models.DateTimeField(db_column='CreatedOn', default=datetime.datetime(2023, 11, 22, 14, 40, 11, 120684, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='modifiedon',
            field=models.DateTimeField(db_column='ModifiedOn', default=datetime.datetime(2023, 11, 22, 14, 40, 11, 120684, tzinfo=datetime.timezone.utc)),
        ),
    ]
