# Generated by Django 4.2.6 on 2023-11-23 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_tax_amount_tblpurchase_details_vat_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblemployee',
            name='health_insurance_expiry',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 15, 45, 40, 840172, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='passport_expiry',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 15, 45, 40, 840172, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='visa_expiry',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 15, 45, 40, 840172, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblpurchase_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 15, 45, 40, 842172, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblsales_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 15, 45, 40, 841177, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='createdon',
            field=models.DateTimeField(db_column='CreatedOn', default=datetime.datetime(2023, 11, 23, 15, 45, 40, 839125, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='modifiedon',
            field=models.DateTimeField(db_column='ModifiedOn', default=datetime.datetime(2023, 11, 23, 15, 45, 40, 839125, tzinfo=datetime.timezone.utc)),
        ),
    ]
