# Generated by Django 4.2.6 on 2023-11-24 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tblusers_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblemployee',
            name='health_insurance_expiry',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 14, 47, 38, 566525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='passport_expiry',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 14, 47, 38, 566525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='visa_expiry',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 14, 47, 38, 566525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblpurchase_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 14, 47, 38, 566525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblpurchase_master',
            name='roundoff',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tblsales_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 14, 47, 38, 566525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='createdon',
            field=models.DateTimeField(db_column='CreatedOn', default=datetime.datetime(2023, 11, 24, 14, 47, 38, 558418, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='modifiedon',
            field=models.DateTimeField(db_column='ModifiedOn', default=datetime.datetime(2023, 11, 24, 14, 47, 38, 558418, tzinfo=datetime.timezone.utc)),
        ),
    ]
