# Generated by Django 4.2.6 on 2023-12-08 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tblpurchase_details_previous_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsales_details',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tblsales_details',
            name='unit',
            field=models.CharField(default='pcs', max_length=10),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='health_insurance_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 16, 48, 18, 791862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='passport_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 16, 48, 18, 791862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='visa_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 16, 48, 18, 791862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblpurchase_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 16, 48, 18, 791862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblsales_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 16, 48, 18, 791862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='createdon',
            field=models.DateTimeField(db_column='CreatedOn', default=datetime.datetime(2023, 12, 8, 16, 48, 18, 791862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='modifiedon',
            field=models.DateTimeField(db_column='ModifiedOn', default=datetime.datetime(2023, 12, 8, 16, 48, 18, 791862, tzinfo=datetime.timezone.utc)),
        ),
    ]
