# Generated by Django 4.2.6 on 2023-12-11 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tblemployee_health_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblpurchase_master',
            name='discount_description',
        ),
        migrations.RemoveField(
            model_name='tblsales_master',
            name='discount_description',
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='health_insurance_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 11, 58, 37, 401706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='passport_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 11, 58, 37, 401706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='visa_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 11, 58, 37, 401706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblpurchase_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 11, 58, 37, 401706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblsales_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 11, 58, 37, 401706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='createdon',
            field=models.DateTimeField(db_column='CreatedOn', default=datetime.datetime(2023, 12, 11, 11, 58, 37, 401706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='modifiedon',
            field=models.DateTimeField(db_column='ModifiedOn', default=datetime.datetime(2023, 12, 11, 11, 58, 37, 401706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='tblSalesReturn_Master',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('return_no', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('return_date', models.DateField(default=datetime.datetime(2023, 12, 11, 11, 58, 37, 401706, tzinfo=datetime.timezone.utc))),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roundoff', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_payed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(default='cash', max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblcustomer')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblemployee')),
            ],
        ),
        migrations.CreateModel(
            name='tblSalesReturn_Details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('vat_perc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('item_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblproduct')),
                ('sales_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tblsalesreturn_master')),
            ],
        ),
        migrations.CreateModel(
            name='tblPurchaseReturn_Master',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purchase_no', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('return_no', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('invoice_date', models.DateField(default=datetime.datetime(2023, 12, 11, 11, 58, 37, 401706, tzinfo=datetime.timezone.utc))),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roundoff', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(default='cash', max_length=15)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblemployee')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblvendor')),
            ],
        ),
        migrations.CreateModel(
            name='tblPurchaseReturn_Details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('vat_perc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('item_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblproduct')),
                ('purchase_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tblpurchasereturn_master')),
            ],
        ),
    ]
