# Generated by Django 4.2.6 on 2023-12-11 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_tblpurchasereturn_master_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblemployee',
            name='health_insurance_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 18, 37, 40, 116096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='passport_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 18, 37, 40, 116096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='visa_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 18, 37, 40, 116096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblpurchase_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 18, 37, 40, 116096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblpurchasereturn_master',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 18, 37, 40, 116096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblsales_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 18, 37, 40, 116096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblsalesreturn_master',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 11, 18, 37, 40, 116096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblsalesreturn_master',
            name='return_no',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='createdon',
            field=models.DateTimeField(db_column='CreatedOn', default=datetime.datetime(2023, 12, 11, 18, 37, 40, 116096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='modifiedon',
            field=models.DateTimeField(db_column='ModifiedOn', default=datetime.datetime(2023, 12, 11, 18, 37, 40, 116096, tzinfo=datetime.timezone.utc)),
        ),
    ]
