# Generated by Django 4.2.6 on 2023-12-12 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_tblemployee_health_insurance_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblpurchasereturn_master',
            name='salesman',
        ),
        migrations.RemoveField(
            model_name='tblpurchasereturn_master',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='tblsalesreturn_details',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tblsalesreturn_details',
            name='sales_return',
        ),
        migrations.RemoveField(
            model_name='tblsalesreturn_master',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tblsalesreturn_master',
            name='salesman',
        ),
        migrations.AddField(
            model_name='tblpurchase_master',
            name='return_no',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tblsales_master',
            name='return_no',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblcustomer',
            name='customer_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='health_insurance_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 12, 15, 1, 34, 310590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='passport_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 12, 15, 1, 34, 310590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='visa_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 12, 15, 1, 34, 310590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblproduct',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tblpurchase_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 12, 15, 1, 34, 310590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblpurchase_master',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblsales_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 12, 15, 1, 34, 310590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblsales_master',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='createdon',
            field=models.DateTimeField(db_column='CreatedOn', default=datetime.datetime(2023, 12, 12, 15, 1, 34, 310590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='modifiedon',
            field=models.DateTimeField(db_column='ModifiedOn', default=datetime.datetime(2023, 12, 12, 15, 1, 34, 310590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblvendor',
            name='vendor_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='tblPurchaseReturn_Details',
        ),
        migrations.DeleteModel(
            name='tblPurchaseReturn_Master',
        ),
        migrations.DeleteModel(
            name='tblSalesReturn_Details',
        ),
        migrations.DeleteModel(
            name='tblSalesReturn_Master',
        ),
    ]
