# Generated by Django 4.2.6 on 2023-12-16 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tblpurchase_master_transaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblExpense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expense_no', models.IntegerField(blank=True, default=0, null=True)),
                ('expense', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('payment_method', models.CharField(default='cash', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='health_insurance_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 18, 58, 36, 422336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='passport_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 18, 58, 36, 422336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblemployee',
            name='visa_expiry',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 18, 58, 36, 422336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblpurchase_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 18, 58, 36, 422336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblsales_master',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 18, 58, 36, 422336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='createdon',
            field=models.DateTimeField(db_column='CreatedOn', default=datetime.datetime(2023, 12, 16, 18, 58, 36, 422336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='modifiedon',
            field=models.DateTimeField(db_column='ModifiedOn', default=datetime.datetime(2023, 12, 16, 18, 58, 36, 422336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='tblReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receipt_no', models.IntegerField(blank=True, default=0, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('payment_method', models.CharField(default='cash', max_length=15)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='tblPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_no', models.IntegerField(blank=True, default=0, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('payment_method', models.CharField(default='cash', max_length=15)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tblvendor')),
            ],
        ),
    ]
